event/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', AdminIndex.as_view(), name="index"),
    url(r'^add/$', addEvent, name="add"),
    url(r'^test/$', test, name="test")

]

operations/urls.py
from django.conf.urls import url
from views import *

urlpatterns=[
   url(r'^login/$',loginUser,name='user_login'),
   url(r'^register/$',registerUser,name='user_register'),
   url(r'^logout/$',logoutUser,name='user_logout'),
   url(r'^bootstrap/$',bootStrap,name='bootstrap_data'),
   url(r'^$',Landing.as_view(),name="landing"),
   url(r'^robots\.txt/$', TemplateView.as_view(template_name='general/robots.txt', content_type='text/plain')),
   url(r'about/^$',About.as_view(),name="about"),

]

tabmgnt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from settings import REST_PREURL

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('operations.urls', namespace='ops')),
    url(r'^superUser/', include('superUser.urls', namespace='superUser')),


    url(r'^'+REST_PREURL+'user/', include('appUser.api.urls', namespace='user_api')),
    url(r'^'+REST_PREURL+'event/', include('event.api.urls', namespace='event_api')),
    url(r'^'+REST_PREURL+'public/', include('public.api.urls', namespace='event_api')),
]

templates/layouts/admin/_footer.html
<footer>
{#<div class="container">#}
{##}
{#	<!-- COMPANY ADDRESS-->#}
{#	<div class="col-md-5 company-details">#}
{#		<div class="icon-top red-text">#}
{#		    <i class="icon-fontawesome-webfont-302"></i>#}
{#		</div>#}
{#		PO Box 16122 Collins Street West, Victoria 8007 Australia#}
{#	</div>#}
{##}
{#	<!-- COMPANY EMAIL-->#}
{#	<div class="col-md-2 company-details">#}
{#		<div class="icon-top green-text">#}
{#		<i class="icon-fontawesome-webfont-329"></i>#}
{#		</div>#}
{#		 contact@designlab.co#}
{#	</div>#}
{##}
{#	<!-- COMPANY PHONE NUMBER -->#}
{#	<div class="col-md-2 company-details">#}
{#		<div class="icon-top blue-text">#}
{#		<i class="icon-fontawesome-webfont-101"></i>#}
{#		</div>#}
{#		+613 0000 0000#}
{#	</div>#}
{##}
{#	<!-- SOCIAL ICON AND COPYRIGHT -->#}
{#	<div class="col-lg-3 col-sm-3 copyright">#}
{#		<ul class="social">#}
{#			<li><a href=""><i class="icon-facebook"></i></a></li>#}
{#			<li><a href=""><i class="icon-twitter-alt"></i></a></li>#}
{#			<li><a href=""><i class="icon-linkedin"></i></a></li>#}
{#			<li><a href=""><i class="icon-behance"></i></a></li>#}
{#			<li><a href=""><i class="icon-dribbble"></i></a></li>#}
{#		</ul>#}
{#		 ©2013 Zerif LLC#}
{#	</div>#}
{#</div> <!-- / END CONTAINER -->#}
</footer>

templates/layouts/admin/_header.html
<header id="home" class="header" style="min-height: 80px">
    {% load staticfiles %}
    <!-- TOP BAR -->
    <div id="main-nav" class="navbar navbar-inverse bs-docs-nav" role="banner">
        <div class="container">
            <div class="navbar-header responsive-logo">
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse"
                        data-target="#bs-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">
                    <h2>WyreList</h2>
                    {#				<img src="{% static 'landingResources/images/logo.png'%}" alt="Zerif">#}
                </div>
            </div>
            <nav class="navbar-collapse collapse" role="navigation" id="bs-navbar-collapse">
                <ul class="nav navbar-nav navbar-right responsive-nav main-nav-list">
                    <li><a href="{% url 'ops:landing' %}">Home</a></li>

                    {% if user.is_authenticated %}
                        <li><a href="{% url 'ops:user_logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'ops:user_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    <!-- / END TOP BAR -->

    <!-- BIG HEADING WITH CALL TO ACTION BUTTONS AND SHORT MESSAGES -->
    <!-- / END BIG HEADING WITH CALL TO ACTION BUTTONS AND SHORT MESSAGES  -->

</header> <!-- / END HOME SECTION  -->

templates/layouts/admin/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}

    <!-- =========================
     FAV AND TOUCH ICONS
    ============================== -->
    <link rel="shortcut icon" href="{% static 'landingResources/images/icons/favicon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'landingResources/images/icons/apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72"
          href="{% static 'landingResources/images/icons/apple-touch-icon-74x74.png' %}">
    <link rel="apple-touch-icon" sizes="114x114"
          href="{% static 'landingResources/images/icons/apple-touch-icon-114x114.png' %}">

    <!-- =========================
         STYLESHEETS
    ============================== -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="{% static 'landingResources/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'landingResources/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'landingResources/css/jquery.vegas.min.css' %}">
    <link rel="stylesheet" href="{% static 'landingResources/css/animate.min.css' %}">

    <link rel="stylesheet" href="{% static 'landingResources/assets/icon-fonts/styles.css' %}">
    <link rel="stylesheet" href="{% static 'landingResources/css/pixeden-icons.css' %}">

    <!-- CUSTOM STYLES -->
    <link rel="stylesheet" href="{% static 'landingResources/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'landingResources/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'landingResources/css/datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'landingResources/css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'landingResources/css/awesome-bootstrap-checkbox.css' %}">

    <!-- WEBFONT -->
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,400italic|Montserrat:700,400|Homemade+Apple'
          rel='stylesheet' type='text/css'>

    <!--[if lt IE 9]>
{#			<script src="js/html5shiv.js"></script>#}
{#			<script src="js/respond.min.js"></script>#}
		<![endif]-->

    <!-- JQUERY -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="{% static 'landingResources/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'landingResources/js/jquery.timepicker.min.js' %}"></script>

    {% block staticResources %}
    {% endblock %}
    {% block title %}
        <title>WyreList</title>
    {% endblock %}
</head>
<body>
{% include 'layouts/admin/_header.html' %}
{% block content %}
{% endblock content %}
{% include 'layouts/admin/_footer.html' %}

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="{% static 'landingResources/js/wow.min.js' %}"></script>
<script src="{% static 'landingResources/js/jquery.nav.js' %}"></script>
<script src="{% static 'landingResources/js/jquery.knob.js' %}"></script>
<script src="{% static 'landingResources/js/owl.carousel.min.js' %}"></script>
{#<script src="{% static 'landingResources/js/smoothscroll.js' %}"></script>#}
<script src="{% static 'landingResources/js/jquery.vegas.min.js' %}"></script>
<script src="{% static 'landingResources/js/zerif.js' %}"></script>


</body>
</html>