event/api/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', GetEventList.as_view(), name='event_list'),
    url(r'^create/$', CreateEvent.as_view(), name='event_create'),
    url(r'^(?P<eventId>[\w-]+)/$', GetEvent.as_view(), name='event_detail')
]

event/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', AdminIndex.as_view(), name="index"),
    url(r'^add/$', addEvent, name="add"),
    url(r'^test/$', test, name="test")

]

tabmgnt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from settings import REST_PREURL

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('operations.urls', namespace='ops')),
    url(r'^superUser/', include('superUser.urls', namespace='superUser')),


    url(r'^'+REST_PREURL+'user/', include('appUser.api.urls', namespace='user_api')),
    url(r'^'+REST_PREURL+'event/', include('event.api.urls', namespace='event_api')),
    url(r'^'+REST_PREURL+'public/', include('public.api.urls', namespace='event_api')),
]

event/models.py
from django.db import models
from contact.models import *
from appUser.models import AppUser
from choices import *
import portfolioFile.services as fileService
import uuid
import logging
logging.basicConfig()
import json
log=logging.getLogger(__name__)


class EventRule(models.Model):
    entryType = models.CharField(choices=EntryType.entryChoices, null=False, default=EntryType.SINGLE, max_length=20)
    entryChargeable = models.BooleanField(default=False)
    feesPerEntry = models.FloatField(null=True,default=0)
    dateOfEvent = models.DateField(null=False)
    duration=models.IntegerField(null=False,default=1)
    startingTime = models.TimeField(null=False)
    endingTime = models.TimeField(null=True)


class Event(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    createdBy = models.ForeignKey(AppUser, null=False)
    description = models.CharField(null=False, max_length=1000)
    location = models.ForeignKey(Address, null=False)
    contact_number = models.ManyToManyField(ContactNumber, null=False)
    eventRule = models.OneToOneField(EventRule)
    totalEntries=models.IntegerField(null=False,blank=True,default=100)
    dateCreated = models.DateTimeField(auto_now_add=True)
    lastUpdated = models.DateTimeField(auto_now=True)


    def nearby_locations(self):
        try:
            nearbyLocations=[]
            locations=EventAmenity.objects.filter(event=self,priority__in=[0,1,2,3]).values()
            for location in locations:
                res=dict()
                res['location']=location
                address=Address.objects.get(id=location['location_id'])
                res['line1']=address.line1
                res['line2']=address.line2
                res['latitude']=address.latitude
                res['longitude']=address.longitude
                nearbyLocations.append(res)
            return nearbyLocations
        except Exception as e:
            log.error(e)
            return None

    def event_normalImages(self):
        try:
            # print(hasattr(self,'eventImages'))
            eventImage=self.eventimage_set.values()[0]
            # for image in eventImages:
            eventImage['image']=fileService.convert_toS3_url(eventImage['image'])
            return eventImage
        except Exception as e:
            log.error(e)
            return None

    @classmethod
    def create(cls, description, createdBy, location, contact_number, eventRule):
        try:
            event = cls(
                createdBy=createdBy,
                location=location,
                eventRule=eventRule,
                description=description
            )
            event.save()
            event.contact_number.add(contact_number)
            return event
        except Exception as e:
            print(e)

class EventImage(models.Model):
    event=models.ForeignKey(Event,null=False, unique=False)
    image = models.ImageField(null=True, upload_to=fileService.get_event_upload_path)
    type=models.CharField(choices=ImageType.imageTypeChoices,default=ImageType.NORMAL,max_length=15)

    @classmethod
    def createMultipleInstances(cls,event,portfolioImage):
        for i in portfolioImage:
            imageInstance=cls(event=event,
                       image=i,
                       type=ImageType.NORMAL)
            imageInstance.save()


class EventAmenity(models.Model):
    event=models.ForeignKey(Event,null=False, unique=False)
    type=models.CharField(choices=AmenityType.amenityTypeChoices,default=AmenityType.NONE,max_length=20)
    location = models.ForeignKey(Address, null=False)
    priority=models.IntegerField(null=False,default=0)


class EventTicket(models.Model):
    event=models.ForeignKey(Event,null=False,unique=False)
    user=models.ForeignKey(AppUser, null=False,unique=False)
    totalTickets=models.IntegerField(null=False)

event/forms.py
from django import forms
from models import Event, EventRule, EventImage


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('description', 'createdBy','totalEntries')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
        }


class EventImageForm(forms.ModelForm):
    class Meta:
        model = EventImage
        fields = ('image',)


class EventRuleForm(forms.ModelForm):
    class Meta:
        model = EventRule
        fields = '__all__'

    def clean_feesPerEntry(self):
        entryChargeable = self.cleaned_data.get('entryChargeable')
        feesPerEntry=self.cleaned_data['feesPerEntry']
        if entryChargeable and not feesPerEntry:
            raise forms.ValidationError("Entry Fees Required when Entry Chargeable is checked")
        return feesPerEntry

event/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView, CreateAPIView
from rest_framework.views import APIView
from serializers import EventSerializer, EventCreateSerializer
from event.models import Event
from event.api.filters import EventFilter
from rest_framework.permissions import IsAuthenticated

class GetEventList(ListAPIView):
    # permission_classes = (IsAuthenticated,)
    serializer_class = EventSerializer
    queryset = Event.objects.all()
    filter_class = EventFilter


class GetEvent(RetrieveAPIView):
    serializer_class = EventSerializer
    queryset = Event.objects.all()
    lookup_field = "uuid"
    lookup_url_kwarg = "eventId"


class CreateEvent(CreateAPIView):
    queryset = Event.objects.all()
    serializer_class = EventCreateSerializer

event/views.py
from django.forms.models import modelformset_factory
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.generic import ListView
from models import Event, EventImage, EventAmenity
from forms import EventForm, EventRuleForm, EventImageForm, EventImage
from contact.forms import *
from event.choices import *
import service as eventService
from django.contrib.auth.decorators import user_passes_test
from tabmgnt.customMixins import SuperuserRequiredMixin
from common.service import google


class AdminIndex(SuperuserRequiredMixin, ListView):
    model = Event
    context_object_name = "events"
    template_name = "index.html"


@user_passes_test(lambda u: u.is_superuser)
def addEvent(request):
    images = request.FILES.getlist('eventImages')
    eventForm = EventForm(request.POST or None)
    eventRuleForm = EventRuleForm(request.POST or None)
    addressForm = AddressForm(request.POST or None)
    contactForm = ContactForm(request.POST or None)
    if eventForm.is_valid() and eventRuleForm.is_valid() and addressForm.is_valid() and contactForm.is_valid():
        event = eventService.createEvent(eventForm, eventRuleForm, addressForm, contactForm)
        if event:
            if (images):
                EventImage.createMultipleInstances(event, images)
            return redirect(reverse("superUser:event:index"))
    else:
        print(contactForm.errors, eventForm.errors, eventRuleForm.errors, addressForm.errors)
    return render(request, "add.html",
                  {'eventForm': eventForm, 'eventRuleForm': eventRuleForm, 'addressForm': addressForm,
                   'contactForm': contactForm})


# Create your views here.
@user_passes_test(lambda u: u.is_superuser)
def test(request):
    events = Event.objects.all()
    EventAmenity.objects.all().delete()
    for event in events:
        latitude = event.location.latitude
        longitude = event.location.longitude
        for amenity in AmenityType.googleMapingChoices:
            if amenity[0] in AmenityType.distanceBasedList:
                response = google.nearByPlace(amenity[1], 10000, SearchDistanceFactor.DISTANCE, latitude=latitude,
                                              longitude=longitude)
            else:
                response = google.nearByPlace(amenity[1], 10000, SearchDistanceFactor.RATING, latitude=latitude,
                                              longitude=longitude)

            response = response['results']
            print"============="+str(response)
            for priority, i in enumerate(response):
                address = Address()
                address.line1 = i['name']
                address.line2 = i['vicinity']
                address.latitude = i['geometry']['location']['lat']
                address.longitude = i['geometry']['location']['lng']
                address.save()
                EventAmenity.objects.create(location=address,
                                            type=amenity[0],
                                            event=event,
                                            priority=priority)

event/templates/_leftPanel.html
<div class="col-md-3">
    <div class="row">

        <a href="{% url 'superUser:event:index' %}" style="width: 100%" type="button" class="btn btn-default">
            All Events
        </a>
    </div>
    <div class="row">
        <a href="{% url 'superUser:event:add' %}" style="width: 100%" type="button" class="btn btn-default">Add
            Events</a>
    </div>
</div>

event/templates/add.html
{% extends 'layouts/admin/main.html' %}
{% load widget_tweaks %}

{% block staticResources %}
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&key=AIzaSyDuM08PJs00SK8Xyclb0DKaWz0_sMFtqwI"></script>
    <style>
        .marginStyle {
            margin-top: 20px
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid" id="container-fluid" style="margin-top: 50px;padding-top: 30px">
        {% include '_leftPanel.html' %}
        <div class="col-md-9">
            <form action="{% url 'superUser:event:add' %}" method="post" enctype="multipart/form-data">
                <div class="row marginStyle">

                    <div class="col-md-6">
                        <div class="col-md-6">
                            Contact Number
                        </div>
                        <div class="col-md-6">
                            {{ contactForm.number|attr:"class:form-control" }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="col-md-6">
                            Contact Type
                        </div>
                        <div class="col-md-6">
                            {{ contactForm.type|attr:"class:form-control" }}
                        </div>
                        {{ form.description|attr:"class:form-control" }}
                    </div>
                </div>
                <div class="row marginStyle">
                    <div class="col-md-12">
                        <div class="col-md-3">
                            Line 1
                        </div>
                        <div class="col-md-9">
                            {{ addressForm.line1|attr:"class:form-control" }}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-3">
                            Line 2
                        </div>
                        <div class="col-md-9">
                            {{ addressForm.line2|attr:"class:form-control" }}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-3">
                            Area
                        </div>
                        <div class="col-md-9">
                            {{ addressForm.location|attr:"class:form-control" }}
                            <input type="hidden" name="latitude" value="{{ addressForm.latitude.value }}" id="latitude">
                            <input type="hidden" name="longitude" id="longitude" value="{{ addressForm.longitude.value }}">
                            <input type="hidden" name="city" id="city" value="{{ addressForm.city.value }}">
                            <input type="hidden" name="state" id="state" value="{{ addressForm.state.value }}">

                        </div>
                    </div>


                </div>
                <div class="row marginStyle">
                    <div class="col-md-6">
                        <div class="col-md-6">
                            Entry Type
                        </div>
                        <div class="col-md-6">
                            {{ eventRuleForm.entryType|attr:"class:form-control" }}
                        </div>

                    </div>

                    <div class="col-md-6">
                        <div class="col-md-6">
                            Entry Chargeable
                        </div>
                        <div class="col-md-6">
                            {{ eventRuleForm.entryChargeable|attr:"class:form-control" }}
                        </div>

                    </div>

                    <div class="col-md-6">
                        <div class="col-md-6">
                            Fees Per Entry
                        </div>
                        <div class="col-md-6">
                            {{ eventRuleForm.feesPerEntry|attr:"class:form-control" }}
                        </div>

                    </div>

                    <div class="col-md-6">
                        <div class="col-md-6">
                            Date Of Event
                        </div>
                        <div class="col-md-6">
                            {{ eventRuleForm.dateOfEvent|attr:"class:form-control" }}
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="col-md-6">
                           Duration (In Days)
                        </div>
                        <div class="col-md-6">
                            {{ eventRuleForm.duration|attr:"class:form-control" }}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="col-md-6">
                            Event Start Time
                        </div>
                        <div class="col-md-6">
                            {{ eventRuleForm.startingTime|attr:"class:form-control" }}
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="col-md-6">
                            Event End Time
                        </div>
                        <div class="col-md-6">
                            {{ eventRuleForm.endingTime|attr:"class:form-control" }}
                        </div>
                    </div>


                    {#                    <div class="col-md-12">#}
                    {#                        <div class="col-md-6">#}
                    {#                            Entry Per Fees(Leave emtpy if free)#}
                    {#                        </div>#}
                    {#                        <div class="col-md-6">#}
                    {#                            {{ eventRuleForm.feesPerEntry|attr:"class:form-control" }}#}
                    {#                        </div>#}
                    {#                    </div>#}
                </div>
                <div class="row marginStyle">
                    <div class="col-md-12">
                        <div class="col-md-3">
                            Created By
                        </div>
                        <div class="col-md-9">
                            {{ eventForm.createdBy|attr:"class:form-control" }}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-3">
                            Event Description
                        </div>
                        <div class="col-md-9">
                            {{ eventForm.description|attr:"class:form-control" }}
                        </div>
                    </div>
                   <div class="col-md-12">
                        <div class="col-md-3">
                            Images
                        </div>
                        <div class="col-md-3">
                            <input type="file" name="eventImages" multiple class="form-control">
                        </div>
                       <div class="col-md-3">
                            Total Tickets
                        </div>
                        <div class="col-md-3">
                            {{ eventForm.totalEntries|attr:"class:form-control" }}
                        </div>
                    </div>
                </div>
                <div class="row marginStyle">
                    <div class="col-md-9 col-md-offset-3 text-center">
                        <input type="submit" class="btn btn-success btn-lg">
                    </div>
                </div>
            </form>

            <div class="col-md-12">
                {{ eventRuleForm.errors }}
                {{ eventForm.errors }}
                {{ addressForm.errors }}
                {{ contactForm.errors }}

            </div>
        </div>
    </div>
    <script>
        $('#id_dateOfEvent').datepicker({
            format: 'mm/dd/yyyy',
        });
        $('#id_startingTime').timepicker({'timeFormat': 'H:i'});
        $('#id_endingTime').timepicker({'timeFormat': 'H:i'});
        var options = {componentRestrictions: {country: 'in'}};
        var element = document.getElementById('id_location');
        var autocomplete = new google.maps.places.Autocomplete(element, options);
        var city, state, latitude, longitude
        google.maps.event.addListener(autocomplete, 'place_changed', function () {
            var place = autocomplete.getPlace();
            var components = place.address_components;
            for (var i in components) {
                if (components[i].types[0] == "locality") {
                    city = components[i].long_name;
                }
                else if (components[i].types[0] == "administrative_area_level_1") {
                    state = components[i].long_name;
                }
            }
            latitude = place.geometry.location.lat();
            longitude = place.geometry.location.lng();
            $('#latitude').val(latitude);
            $('#longitude').val(longitude);
            $('#city').val(city);
            $('#state').val(state);

        })
    </script>
{% endblock content %}

event/templates/index.html
{% extends 'layouts/admin/main.html' %}

{% block content %}
    <div class="container-fluid" style="margin-top: 50px;">
        {% include '_leftPanel.html' %}
        <div class="col-md-9">
            <table class="table">
                <thead>
                <th>Created By</th>
                <th>Created On</th>
                <th>Location</th>
                <th>Contact</th>

                </thead>
                <tbody>
                {% for i in events %}
                    <tr>
                        <td>{{ i.createdBy }}</td>
                        <td>{{ i.dateCreated }}</td>
                        <td>{{ i.location }}</td>
                        <td>{% if i.contact_number.first %}
                            {% for contact in i.contact_number.all %}
                                {{ contact | default:"Not Added" }}
                            {% endfor %}
                        {% endif %}
                            {% if not i.contact_number.first %}
                                Not Added
                            {% endif %}
                        </td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock content %}